name: map_launcher
description: Map Launcher is a flutter plugin to find available maps installed on a device and launch them with a marker or show directions.
version: 3.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmiller.map_launcher
        pluginClass: MapLauncherPlugin
      ios:
        pluginClass: MapLauncherPlugin

  assets:
    - assets/icons/
